
[functions.check-email-exists]
enabled = true
verify_jwt = false
import_map = "./functions/check-email-exists/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/check-email-exists/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/check-email-exists/*.html" ]
